packages:
  - 'apps/*'
  - 'packages/*'

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

catalog:
  "@types/node": ^25.0.3
  ethers: ^6.16.0
  typescript: ^5.9.3

  # Testing Dependencies
  vitest: "^4.0.16"
  "@vitest/ui": "^4.0.16"
  "@vitest/browser-playwright": "^4.0.16"
  "@testing-library/react": "^16.3.1"
  "@testing-library/jest-dom": "^6.9.1"
  "@testing-library/user-event": "^14.6.1"
  "msw": "^2.12.7"
  "@playwright/test": "^1.57.0"
  "happy-dom": "^20.0.11"